- name: "2.1.1-2.1.10 | Ensure rsh, rlogin, rexec, talk, telnet, chargen, daytime, echo, discard, time is not enabled (stat inetd)"
  stat: path=/etc/inetd.conf
  register: inetd_path
  tags:
  - id_2.1.1-2.1.10

- name: "2.1.1-2.1.10 | Ensure rsh, rlogin, rexec, talk, telnet, chargen, daytime, echo, discard, time is not enabled"
  lineinfile: >
      dest=/etc/inetd.conf
      regexp='^({{ item }}.*)'
      line='#\1'
      state=present
      backrefs=yes
      backup=yes
  with_items:
      - chargen
      - daytime
      - discard
      - echo
      - time
      - shell
      - login
      - exec
      - talk
      - ntalk
      - telnet
      - tftp
      - xinetd
  when: inetd_path.stat.exists == True
  tags:
  - id_2.1.1-2.1.10

- name: "2.2.1.1 | Ensure time synchronization is in use"
  apt:
      name: ntp
      state: present
  when: ubu14gsa_time_Synchronization == ntp
  tags:
      - id_2.1.1.1

- name: "2.2.1.1 | Ensure time synchronization is in use"
  apt:
      name: chrony
      state: present
  when: ubu14gsa_time_Synchronization == chrony
  tags:
      - id_2.1.1.1

- name: "2.2.2 | Ensure X Window System in not installed"
  apt:
      name: xorg-x11-server-common.x86_64
      state: absent
  tags:
      - id_2.2.2

- name: 2.2.3 | Ensure Avahi Server is not enabled
  lineinfile: >
      line='#start on (filesystem'
      state=present
      regexp='start on \(filesystem'
      dest=/etc/init/avahi-daemon.conf
  when: avahi_stat.stat.exists == True
  tags:
    - id_2.2.3

- name: 2.2.4 | Ensure print server is not enabled
  lineinfile: >
      line='#start on (filesystem'
      state=present
      regexp='start on \(filesystem'
      dest=/etc/init/cups.conf
  when: cups_stat.stat.exists == True
  tags:
    - id_2.2.4

- name: 2.2.5 | Ensure DHCP Server is not enabled
  lineinfile: >
      line='#start on runlevel [2345]'
      state=present
      regexp='start on runlevel'
      dest=/etc/init/isc-dhcp-server.conf
  when: dhcp_stat.stat.exists == True
  tags:
    - id_2.2.5

- name: 2.2.6 | Ensure LDAP is not enabled
  apt: name=slapd purge=yes state=absent
  tags:
    - id_2.2.6

- name: 2.7.2 | Ensure NFS is not enabled (rc.d)
  service: >
      name=nfs-kernel-server
      enabled=no
  when: nfs_present is defined and nfs_present.rc == 0
  register: nfs_service_result
  failed_when: "nfs_service_result|failed and 'service not found' not in nfs_service_result.msg"
  tags:
    - id_2.7.2

- name: 2.7.2 | Ensure RPC is not enabled (rc.d) 
  service: >
      name=rpcbind
      enabled=no
  when: nfs_present is defined and nfs_present.rc == 0
  register: rpc_service_result
  failed_when: "rpc_service_result|failed and 'service not found' not in rpc_service_result.msg"
  tags:
    - section2
    - section2.7
    - section2.7.2

- name: "2.2.8 | Ensure DNS Server is not enabled"
  service:
      name: named
      state: stopped
      enabled: no
  when: ubu14gsa_named_server == false and named_service_status.stdout == "loaded"
  tags:
      - id_2.2.8

- name: "2.2.9 | Ensure FTP Server is not enabled"
  service:
      name: vsftpd
      state: stopped
      enabled: no
  when: ubu14gsa_vsftpd_server == false and vsftpd_service_status.stdout == "loaded"
  tags:
      - id_2.2.9

- name: "2.2.10 | Ensure HTTP server is not enabled"
  service:
      name: httpd
      state: stopped
      enabled: no
  when: ubu14gsa_httpd_server == false and httpd_service_status.stdout == "loaded"
  tags:
      - id_2.2.10

- name: "2.2.11 | Ensure IMAP and POP3 server is not enabled"
  service:
      name: dovecot
      state: stopped
      enabled: no
  when: ubu14gsa_dovecot_server == false and dovecot_service_status.stdout == "loaded"
  tags:
      - id_2.2.11

- name: "2.2.12 | Ensure Samba is not enabled"
  service:
      name: smbd
      state: stopped
      enabled: no
  when: ubu14gsa_smb_server == false and smb_service_status.stdout == "loaded"
  tags:
      - id_2.2.12

- name: "2.2.13 | Ensure HTTP Proxy Server is not enabled"
  service:
      name: squid3
      state: stopped
      enabled: no
  when: ubu14gsa_squid_server == false and squid_service_status.stdout == "loaded"
  tags:
      - id_2.2.13

- name: "2.2.14 | Ensure SNMP Server is not enabled"
  service:
      name: snmpd
      state: stopped
      enabled: no
  when: ubu14gsa_snmp_server == false and snmpd_service_status.stdout == "loaded"
  tags:
      - id_2.2.14

- name: "2.2.17 | Ensure NIS Server is not enabled"
  service:
      name: ypserv
      state: stopped
      enabled: no
  when: ubu14gsa_nis_server == false and ypserv_service_status.stdout == "loaded"
  tags:
      - id_2.2.17

- name: "2.2.17 | Ensure rsh server is not enabled | rsh"
  service:
      name: rsh.socket
      state: stopped
      enabled: no
  when: ubu14gsa_rsh_server == false and rsh_service_status.stdout == "loaded"
  tags:
      - id_2.2.17

- name: "2.2.17 | Ensure rsh server is not enabled | rlogin"
  service:
      name: rlogin.socket
      state: stopped
      enabled: no
  when: ubu14gsa_rsh_server == false and rlogin_service_status.stdout == "loaded"
  tags:
      - id_2.2.17

- name: "2.2.17 | Ensure rsh server is not enabled | rexec"
  service:
      name: rexec.socket
      state: stopped
      enabled: no
  when: ubu14gsa_rsh_server == false and rexec_service_status.stdout == "loaded"
  tags:
      - id_2.2.17

- name: "2.2.18 | Ensure talk server is not enabled"
  service:
      name: ntalk
      state: stopped
      enabled: no
  when: ubu14gsa_ntalk_server == false and ntalk_service_status.stdout == "loaded"
  tags:
      - id_2.2.18

- name: "2.2.19 | Ensure telnet server is not enabled"
  service:
      name: telnet
      state: stopped
      enabled: no
  when: ubu14gsa_telnet_server == false and telnet_service_status.stdout == "loaded"
  tags:
      - id_2.2.19

- name: "2.2.20 | Ensure tftp server is not enabled"
  service:
      name: tftp
      state: stopped
      enabled: no
  when: ubu14gsa_tftp_server == false and tftp_service_status.stdout == "loaded"
  tags:
      - insecure_services
      - tftp
      - id_2.2.20

- name: "2.2.21 | Ensure rsync service is not enabled "
  service:
      name: rsyncd
      state: stopped
      enabled: no
  when: ubu14gsa_rsyncd_server == false and rsyncd_service_status.stdout == "loaded"
  tags:
      - id_2.2.21

- name: "2.2.21 | Ensure talk server is not enabled"
  service:
      name: ntalk
      state: stopped
      enabled: no
  when: ubu14gsa_ntalk_server == false and ntalk_service_status.stdout == "loaded"
  tags:
      - id_2.2.21

- name: "2.3.1 | Ensure NIS Client is not installed"
  apt:
      name: ypbind
      state: absent
  when: ubu14gsa_ypbind_required == false
  tags:
      - id_2.3.1

- name: "2.3.2 | Ensure rsh client is not installed"
  apt:
      name: rsh
      state: absent
  when: ubu14gsa_rsh_required == false
  tags:
      - id_2.3.2

- name: "2.3.3 | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when: ubu14gsa_talk_required == false
  tags:
      - id_2.3.3

- name: "2.3.4 | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when: ubu14gsa_telnet_required == false
  tags:
      - id_2.3.4

- name: "2.3.5 | Ensure LDAP client is not installed"
  apt:
      name: openldap-clients
      state: absent
  when: ubu14gsa_openldap_clients_required == false
  tags:
      - id_2.3.5
