- name: "1.6.2.1 | Ensure AppArmor is not disabled in bootloader configuration"
  lineinfile:
      dest: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX="
      line: "GRUB_CMDLINE_LINUX=apparmor="1 security=apparmor"
      state: present
  when: use_apparmor == "true"
  tags:
    - id_1.6.2.1
