- name: "2.2.3 | Ensure Avahi Server is not enabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: no
  when: ubu14gsa_avahi_server == false and avahi_service_status.stdout == "loaded"
  tags:
      - avahi
      - services
      - id_2.2.3

- name: "2.2.4 | Ensure CUPS is not enabled"
  service:
      name: cups
      state: stopped
      enabled: no
  when: ubu14gsa_cups_server == false and cups_service_status.stdout == "loaded"
  tags:
      - cups
      - services
      - id_2.2.4

- name: "2.2.5 | Ensure DHCP Server is not enabled"
  service:
      name: dhcpd
      state: stopped
      enabled: no
  when: ubu14gsa_dhcp_server == false and dhcpd_service_status.stdout == "loaded"
  tags:
      - dhcp
      - services

      - id_2.2.5

- name: "2.2.6 | Ensure LDAP server is not enabled"
  service:
      name: slapd
      state: stopped
      enabled: no
  when: ubu14gsa_ldap_server == false and slapd_service_status.stdout == "loaded"
  tags:
      - ldap
      - services
      - id_2.2.6

- name: "2.2.7 | Ensure NFS and RPC are not enabled"
  service:
      name: nfs
      state: stopped
      enabled: no
  when: ubu14gsa_nfs_rpc_server == false and nfs_service_status.stdout == "loaded"
  tags:
      - nfs
      - rpc
      - services
      - id_2.2.7

- name: "2.2.7 | Ensure NFS and RPC are not enabled"
  service:
      name: rpcbind
      state: stopped
      enabled: no
  when: ubu14gsa_nfs_rpc_server == false and rpcbind_service_status.stdout == "loaded"
  tags:
      - nfs
      - rpc
      - services
      - id_2.2.7

- name: "2.2.8 | Ensure DNS Server is not enabled"
  service:
      name: named
      state: stopped
      enabled: no
  when: ubu14gsa_named_server == false and named_service_status.stdout == "loaded"
  tags:
      - id_2.2.8

- name: "2.2.9 | Ensure FTP Server is not enabled"
  service:
      name: vsftpd
      state: stopped
      enabled: no
  when: ubu14gsa_vsftpd_server == false and vsftpd_service_status.stdout == "loaded"
  tags:
      - id_2.2.9

- name: "2.2.10 | Ensure HTTP server is not enabled"
  service:
      name: httpd
      state: stopped
      enabled: no
  when: ubu14gsa_httpd_server == false and httpd_service_status.stdout == "loaded"
  tags:
      - id_2.2.10
